services:
  frontend:
    image: node:20
    container_name: frontend
    working_dir: /src
    command: sh -c "npm install && npm start"
    ports:
      - "3000:3000"
    volumes:
      - "./frontend:/src"

  backend:
    image: node:20
    container_name: backend
    working_dir: /app
    command: sh -c "npm install && npx prisma migrate deploy  &&  npm run dev"
    environment:
      DATABASE_URL: "postgresql://postgres:root@db:5432/gestionrh?schema=public"
    ports:
      - "5002:5002"
    volumes:
      - "./backend:/app"
  db:
    container_name: db
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: gestionrh
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}